# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_key_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='forgot_pass_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='forgot_pass_key_expires',
            field=models.DateTimeField(null=True),
        ),
    ]
